In [3]:
import numpy as np
import pandas as pd
import os
from datetime import datetime
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv('./data_april_may.csv')
df["Date"] = pd.to_datetime(df["Date"])
df['day'] = df['Date'].dt.date
df["Days_to_Current_Date"] = (datetime.now() - df["Date"]).dt.days

# select days
df_month = df.loc[df['Days_to_Current_Date'] < 31,:]

# Distance to float
df_month['Distance'] = df_month['Distance'].str.replace(',', '.')
df_month.Distance = df_month.Distance.apply(float)

/var/folders/r6/k_cdzkx14flddy2y0tvhd57r0000gn/T/ipykernel_7796/3351875389.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_month['Distance'] = df_month['Distance'].str.replace(',', '.')
/var/folders/r6/k_cdzkx14flddy2y0tvhd57r0000gn/T/ipykernel_7796/3351875389.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_month.Distance = df_month.Distance.apply(float)

In [5]:


# Convert the 'Elapsed_time' column to timedelta
df_month['Elapsed Time'] = pd.to_timedelta(df_month['Elapsed Time'])

# Convert timedelta to minutes
df_month['workout_minutes'] = np.round(df_month['Elapsed Time'].dt.total_seconds()/60)

/var/folders/r6/k_cdzkx14flddy2y0tvhd57r0000gn/T/ipykernel_7796/3515230378.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_month['Elapsed Time'] = pd.to_timedelta(df_month['Elapsed Time'])
/var/folders/r6/k_cdzkx14flddy2y0tvhd57r0000gn/T/ipykernel_7796/3515230378.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_month['workout_minutes'] = np.round(df_month['Elapsed Time'].dt.total_seconds()/60)

In [94]:
# average workout time
# df_month["Elapsed Time"] = pd.to_timedelta(df_month["Elapsed Time"].str.replace(",", "."), errors="coerce")
# average_elapsed_time = df["Elapsed Time"].mean()
# average_elapsed_time_str = str(average_elapsed_time).split()[-1].split('.')[0]

In [95]:
df_month

,Activity Type,Date,Favorite,Title,Distance,Calories,Time,Avg HR,Max HR,Aerobic TE,...,Avg Resp,Min Resp,Max Resp,Moving Time,Elapsed Time,Min Elevation,Max Elevation,day,Days_to_Current_Date,workout_minutes
0,Strength Training,2023-05-25 12:08:59,False,Strength,0.000,82,00:25:44,78,122,"0,1",...,--,--,--,00:25:44,0 days 00:25:44,--,--,2023-05-25,8,26.0
1,Running,2023-05-24 12:09:02,False,Hammersmith and Fulham Running,6.140,407,00:28:43,144,158,"3,2",...,--,--,--,00:28:24,0 days 00:29:42,7,15,2023-05-24,9,30.0
2,Cycling,2023-05-23 19:12:34,False,Camden Cycling,32.010,726,00:55:04,157,182,"3,7",...,36,17,48,00:54:48,0 days 01:00:41,35,56,2023-05-23,10,61.0
3,Pool Swimming,2023-05-22 18:23:30,False,Pool Swimming,4.300,833,01:18:51,146,180,"3,7",...,--,--,--,01:01:18,0 days 01:38:08,--,--,2023-05-22,11,98.0
4,Strength Training,2023-05-22 12:13:32,False,Strength,0.000,136,00:25:18,98,123,"0,4",...,--,--,--,00:25:18,0 days 00:25:18,--,--,2023-05-22,11,25.0
5,Running,2023-05-21 15:02:49,False,Brent Running,10.020,616,00:45:10,147,175,"3,4",...,26,11,43,00:45:07,0 days 00:46:36,29,46,2023-05-21,12,47.0
6,Running,2023-05-19 12:19:10,False,Hammersmith and Fulham Running,7.930,500,00:35:21,144,162,"3,5",...,--,--,--,00:35:17,0 days 00:36:12,9,30,2023-05-19,14,36.0
7,Pool Swimming,2023-05-17 17:54:33,False,Pool Swimming,3.600,732,01:04:30,146,170,"3,6",...,--,--,--,00:50:42,0 days 02:00:40,--,--,2023-05-17,16,121.0
8,Running,2023-05-17 12:31:32,False,Camden Running,6.160,375,00:28:50,143,175,"3,0",...,30,15,41,00:28:44,0 days 00:28:50,34,58,2023-05-17,16,29.0
9,Open Water Swimming,2023-05-13 06:11:54,False,Tinghir Open Water Swimming,0.176,31,"00:08:19,4",135,148,"1,8",...,--,--,--,00:03:01,0 days 00:11:14,--,--,2023-05-13,21,11.0
10,Open Water Swimming,2023-05-12 18:26:26,False,Tinghir Open Water Swimming,0.176,32,"00:08:50,2",113,131,"0,5",...,--,--,--,00:03:41,0 days 00:16:22,--,--,2023-05-12,21,16.0
11,Strength Training,2023-05-11 08:49:08,False,Strength,0.000,58,00:10:40,96,124,"0,2",...,--,--,--,00:10:40,0 days 00:10:40,--,--,2023-05-11,23,11.0
12,Pool Swimming,2023-05-10 17:41:37,False,Pool Swimming,3.400,681,01:08:28,134,164,"2,6",...,--,--,--,00:46:33,0 days 01:21:28,--,--,2023-05-10,23,81.0
13,Running,2023-05-10 11:34:00,False,Brent Running,7.660,451,00:34:20,146,160,"3,1",...,23,12,39,00:34:19,0 days 00:34:20,33,56,2023-05-10,23,34.0
14,Pool Swimming,2023-05-09 18:40:01,False,Pool Swimming,0.650,14,00:16:03,111,128,"0,5",...,--,--,--,00:14:23,0 days 01:16:29,--,--,2023-05-09,24,76.0
15,Strength Training,2023-05-09 12:11:55,False,Strength,0.000,58,00:25:04,73,101,"0,0",...,--,--,--,00:25:04,0 days 00:25:04,--,--,2023-05-09,24,25.0
16,Running,2023-05-08 19:17:57,False,Brent Running,4.950,287,00:20:51,151,166,"3,0",...,28,17,40,00:20:38,0 days 00:20:51,39,55,2023-05-08,25,21.0
17,Cycling,2023-05-08 09:26:43,False,Camden Cycling,44.000,906,01:30:30,131,175,"2,9",...,29,17,42,01:29:39,0 days 01:43:34,16,53,2023-05-08,26,104.0
18,Pool Swimming,2023-05-07 15:24:42,False,Pool Swimming,4.000,692,01:21:36,117,148,"2,1",...,--,--,--,00:57:07,0 days 01:24:44,--,--,2023-05-07,26,85.0
19,Running,2023-05-06 19:19:41,False,Brent Running,5.290,346,00:25:47,132,155,"3,2",...,--,--,--,00:25:16,0 days 00:25:49,33,52,2023-05-06,27,26.0
20,Elliptical,2023-05-05 17:09:15,False,Elliptical,0.000,401,00:32:36,150,190,"3,3",...,--,--,--,00:00:00,0 days 00:32:36,--,--,2023-05-05,28,33.0
21,Strength Training,2023-05-05 16:24:40,False,Strength,0.000,193,00:42:35,95,116,"0,4",...,--,--,--,00:42:35,0 days 00:42:35,--,--,2023-05-05,28,43.0
22,Pool Swimming,2023-05-04 07:52:23,False,Pool Swimming,3.600,734,00:58:33,107,128,"1,0",...,--,--,--,00:55:49,0 days 01:04:53,--,--,2023-05-04,30,65.0
23,Strength Training,2023-05-03 12:15:40,False,Strength,0.000,60,00:26:53,70,101,"0,1",...,--,--,--,00:26:53,0 days 00:26:53,--,--,2023-05-03,30,27.0

In [97]:
df_month.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24 entries, 0 to 23
Data columns (total 48 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Activity Type             24 non-null     object
 1   Date                      24 non-null     datetime64[ns]
 2   Favorite                  24 non-null     bool
 3   Title                     24 non-null     object
 4   Distance                  24 non-null     float64
 5   Calories                  24 non-null     object
 6   Time                      24 non-null     object
 7   Avg HR                    24 non-null     int64
 8   Max HR                    24 non-null     int64
 9   Aerobic TE                24 non-null     object
 10  Avg Bike Cadence          24 non-null     object
 11  Max Bike Cadence          24 non-null     object
 12  Avg Speed                 24 non-null     object
 13  Max Speed                 24 non-null     object
 14  Total Ascent              24 non-null     object
 15  Total Descent             24 non-null     object
 16  Avg Stride Length         24 non-null     object
 17  Avg Vertical Ratio        24 non-null     object
 18  Avg Vertical Oscillation  24 non-null     object
 19  Avg Ground Contact Time   24 non-null     int64
 20  Avg GCT Balance           24 non-null     object
 21  Training Stress Score®    24 non-null     object
 22  Avg Power                 24 non-null     int64
 23  Max Power                 24 non-null     int64
 24  Grit                      24 non-null     object
 25  Flow                      24 non-null     object
 26  Total Strokes             24 non-null     object
 27  Avg. Swolf                24 non-null     int64
 28  Avg Stroke Rate           24 non-null     int64
 29  Total Reps                24 non-null     int64
 30  Total Sets                24 non-null     object
 31  Dive Time                 24 non-null     object
 32  Min Temp                  24 non-null     object
 33  Surface Interval          24 non-null     object
 34  Decompression             24 non-null     object
 35  Best Lap Time             24 non-null     object
 36  Number of Laps            24 non-null     int64
 37  Max Temp                  24 non-null     object
 38  Avg Resp                  24 non-null     object
 39  Min Resp                  24 non-null     object
 40  Max Resp                  24 non-null     object
 41  Moving Time               24 non-null     object
 42  Elapsed Time              24 non-null     timedelta64[ns]
 43  Min Elevation             24 non-null     object
 44  Max Elevation             24 non-null     object
 45  day                       24 non-null     object
 46  Days_to_Current_Date      24 non-null     int64
 47  workout_minutes           24 non-null     float64
dtypes: bool(1), datetime64[ns](1), float64(2), int64(10), object(33), timedelta64[ns](1)
memory usage: 9.0+ KB

In [99]:
df_month[['day','Activity Type','Distance','workout_minutes','Avg Speed','Max HR','Avg HR']]

,day,Activity Type,Distance,workout_minutes,Avg Speed,Max HR,Avg HR
0,2023-05-25,Strength Training,0.000,26.0,--,122,78
1,2023-05-24,Running,6.140,30.0,4:40,158,144
2,2023-05-23,Cycling,32.010,61.0,"34,9",182,157
3,2023-05-22,Pool Swimming,4.300,98.0,1:24,180,146
4,2023-05-22,Strength Training,0.000,25.0,--,123,98
5,2023-05-21,Running,10.020,47.0,4:31,175,147
6,2023-05-19,Running,7.930,36.0,4:27,162,144
7,2023-05-17,Pool Swimming,3.600,121.0,1:25,170,146
8,2023-05-17,Running,6.160,29.0,4:41,175,143
9,2023-05-13,Open Water Swimming,0.176,11.0,4:43,148,135
10,2023-05-12,Open Water Swimming,0.176,16.0,5:00,131,113
11,2023-05-11,Strength Training,0.000,11.0,--,124,96
12,2023-05-10,Pool Swimming,3.400,81.0,1:23,164,134
13,2023-05-10,Running,7.660,34.0,4:29,160,146
14,2023-05-09,Pool Swimming,0.650,76.0,1:42,128,111
15,2023-05-09,Strength Training,0.000,25.0,--,101,73
16,2023-05-08,Running,4.950,21.0,4:13,166,151
17,2023-05-08,Cycling,44.000,104.0,"29,2",175,131
18,2023-05-07,Pool Swimming,4.000,85.0,1:22,148,117
19,2023-05-06,Running,5.290,26.0,4:53,155,132
20,2023-05-05,Elliptical,0.000,33.0,--,190,150
21,2023-05-05,Strength Training,0.000,43.0,--,116,95
22,2023-05-04,Pool Swimming,3.600,65.0,1:33,128,107
23,2023-05-03,Strength Training,0.000,27.0,--,101,70

In [31]:
print(f'{len(df_month)} workouts in the past 31 days, with an average duration of {average_elapsed_time_str}.')

36 workouts in the past 31 days, with an average duration of 00:55:42

In [57]:

activity_counts = df_month['Activity Type'].value_counts()
activity_means = df_month.groupby('Activity Type')['Elapsed Time'].mean()

print(f'{len(df_month)} workouts in the past 31 days, with an average duration of {average_elapsed_time_str}.')


docstring = """
Activity Type Counts:
{}

Time in minutes spent on each activity:
{}
"""
activity_counts.index.name = None

print(docstring.format(str(activity_counts)[:-len("\nName: count, dtype: int64")],
                      str(activity_means_minutes)[:-len("\nName: Elapsed Time, dtype: int64")]))

36 workouts in the past 31 days, with an average duration of 00:55:42.

Activity Type Counts:
Strength Training      9
Running                8
Pool Swimming          8
Cycling                7
Open Water Swimming    2
Elliptical             2

Time in minutes spent on each activity:
Cycling                81
Elliptical             33
Open Water Swimming     8
Pool Swimming          84
Running                29
Strength Training      25

In [28]:
average_elapsed_time_str.split('.')[0]

'00:55:42'